[tool.poetry]
name = "opsmate"
version = "0.1.0"
description = "opsmate is a SRE AI assistant"
authors = ["Jingkai <jingkai@hey.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
