openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
- url: /
paths:
  /api/v1/health:
    get:
      operationId: health_api_v1_health_get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
          description: Successful Response
      summary: Health
  /api/v1/models:
    get:
      operationId: models_api_v1_models_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Model'
                type: array
          description: Successful Response
      summary: Models
components:
  schemas:
    Health:
      example:
        status: ok
      properties:
        status:
          default: ok
          enum:
          - ok
          - faulty
          title: status
          type: string
      title: Health
    Model:
      example:
        provider: provider
        model: model
      properties:
        provider:
          title: provider
          type: string
        model:
          title: model
          type: string
      required:
      - model
      - provider
      title: Model
