openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
- url: /
paths:
  /api/v1/health:
    get:
      operationId: health_api_v1_health_get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
          description: Successful Response
      summary: Health
  /api/v1/models:
    get:
      operationId: models_api_v1_models_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Model'
                type: array
          description: Successful Response
      summary: Models
  /api/v1/run:
    post:
      operationId: run_api_v1_run_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: object
                type: array
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Run
components:
  schemas:
    HTTPValidationError:
      example:
        detail:
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
      title: HTTPValidationError
    Health:
      example:
        status: ok
      properties:
        status:
          default: ok
          enum:
          - ok
          - faulty
          title: status
          type: string
      title: Health
    Model:
      example:
        provider: provider
        model: model
      properties:
        provider:
          title: provider
          type: string
        model:
          title: model
          type: string
      required:
      - model
      - provider
      title: Model
    RunRequest:
      example:
        provider: provider
        instruction: instruction
        ask: false
        model: model
        contexts:
        - contexts
        - contexts
      properties:
        model:
          title: name of the llm model to use
          type: string
        provider:
          title: name of the provider to use
          type: string
        instruction:
          title: instruction to execute
          type: string
        contexts:
          default:
          - cli
          items:
            type: string
          type: array
        ask:
          default: false
          title: ask
          type: boolean
      required:
      - instruction
      - model
      - provider
      title: RunRequest
    ValidationError:
      example:
        msg: msg
        loc:
        - ValidationError_loc_inner
        - ValidationError_loc_inner
        type: type
      properties:
        loc:
          items:
            $ref: '#/components/schemas/ValidationError_loc_inner'
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ValidationError_loc_inner:
      anyOf:
      - type: string
      - type: integer
