---
apiVersion: v1
kind: Namespace
metadata:
  name: payment
---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: payment-service:v1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health  # Intentionally wrong - endpoint is actually /status
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health  # Also wrong
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
