name: Publish

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'

jobs:
  release-build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pipx install poetry --python $(which python3.12)
      - name: Install project
        run: poetry install
      - name: Build package
        run: |
          poetry build
      - name: upload dists
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f
